const nodes = [
  {
    container: 'nodejs',
    cluster: 'seoul',
    instance: 'seoulb01',
    os: 'rhel7',
  },
  {
    container: 'nodejs',
    cluster: 'seoul',
    instance: 'seoulm01',
    os: 'rhel8',
  },
  {
    container: 'nodejs',
    cluster: 'seoul',
    instance: 'seoulh01',
    os: 'ubuntu',
  },
  {
    container: 'nodejs',
    cluster: 'seoul',
    instance: 'seouln01',
    os: 'rhcos7',
  },
  {
    container: 'nodejs',
    cluster: 'seoul',
    instance: 'seoulm02',
    os: 'centos7',
  },
  {
    container: 'nodejs',
    cluster: 'seoul',
    instance: 'seoulh02',
    os: 'centos8',
  },
  {
    container: 'nodejs',
    cluster: 'seoul',
    instance: 'seouln02',
    os: 'rhcos8',
  },
  {
    container: 'nodejs',
    cluster: 'seoul',
    instance: 'seoulm03',
    os: 'ubuntu',
  },
  {
    container: 'nodejs',
    cluster: 'seoul',
    instance: 'seoulh03',
    os: 'centos7',
  },
  {
    container: 'nodejs',
    cluster: 'seoul',
    instance: 'seouln03',
    os: 'centos8',
  },
  {
    container: 'nodejs',
    cluster: 'seoul',
    instance: 'seouln04',
    os: 'rhcos7',
  },
  {
    container: 'nodejs',
    cluster: 'seoul',
    instance: 'seouln05',
    os: 'rhcos8',
  },
  {
    container: 'nodejs',
    cluster: 'busanoul',
    instance: 'busanb01',
    os: 'rhel8',
  },
  {
    container: 'nodejs',
    cluster: 'busan',
    instance: 'busanm01',
    os: 'rhel7',
  },
  {
    container: 'nodejs',
    cluster: 'busan',
    instance: 'busanh01',
    os: 'rhel7',
  },
  {
    container: 'nodejs',
    cluster: 'busan',
    instance: 'busann01',
    os: 'rhel8',
  },
  {
    container: 'nodejs',
    cluster: 'busan',
    instance: 'busanm02',
    os: 'rhcos7',
  },
  {
    container: 'nodejs',
    cluster: 'busan',
    instance: 'busanh02',
    os: 'rhcos8',
  },
  {
    container: 'nodejs',
    cluster: 'busan',
    instance: 'busann02',
    os: 'centos7',
  },
  {
    container: 'nodejs',
    cluster: 'busan',
    instance: 'busanm03',
    os: 'centos8',
  },
  {
    container: 'nodejs',
    cluster: 'busan',
    instance: 'busanh03',
    os: 'ubuntu',
  },
  {
    container: 'nodejs',
    cluster: 'busan',
    instance: 'busann03',
    os: 'rhel8',
  },
  {
    container: 'nodejs',
    cluster: 'busan',
    instance: 'busann04',
    os: 'centos8',
  },
  {
    container: 'nodejs',
    cluster: 'busan',
    instance: 'busann05',
    os: 'ubuntu',
  },
];

module.exports = { nodes };
